"""
Daily research report generator outputting Markdown and JSON summaries.
"""

import os
import json
import logging
import pandas as pd
from typing import Dict, Any

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates human-readable Markdown research report and machine-readable JSON analysis."""

    def __init__(self, reports_dir: str = "reports/daily", analysis_dir: str = "data/analysis/daily"):
        self.reports_dir = reports_dir
        self.analysis_dir = analysis_dir

    def _fmt_price(self, val: Any, symbol: str = "$") -> str:
        if isinstance(val, (int, float)) and not pd.isna(val):
            return f"{symbol}{val:,.2f}"
        return "N/A"

    def generate_daily_report(
        self,
        target_date: str,
        gold_summary: Dict[str, Any],
        silver_summary: Dict[str, Any],
        ratio_summary: Dict[str, Any],
        macro_summary: Dict[str, Any],
        regime_summary: Dict[str, Any],
        analogue_summary: Dict[str, Any],
        signals_summary: Dict[str, Any],
        scores_summary: Dict[str, Any],
        quality_summary: Dict[str, Any],
    ) -> str:
        """Generates Markdown report at reports/daily/YYYY-MM-DD.md"""

        g_price_str = self._fmt_price(gold_summary.get("price"), "$")
        g_inr_str = self._fmt_price(gold_summary.get("inr_price_10g"), "₹")
        g_move = gold_summary.get("daily_move_pct", 0.0) or 0.0

        s_price_str = self._fmt_price(silver_summary.get("price"), "$")
        s_inr_str = self._fmt_price(silver_summary.get("inr_price_kg"), "₹")
        s_move = silver_summary.get("daily_move_pct", 0.0) or 0.0

        ratio_val = ratio_summary.get("gold_silver_ratio")
        ratio_str = f"{ratio_val:.2f}" if isinstance(ratio_val, (int, float)) and not pd.isna(ratio_val) else "N/A"
        zscore_val = ratio_summary.get("ratio_zscore")
        zscore_str = f"{zscore_val:.2f}" if isinstance(zscore_val, (int, float)) and not pd.isna(zscore_val) else "N/A"

        md = f"""# Precious Metals Daily Research Report
**Date:** {target_date}

> **Disclaimer:** All forecasts and probabilities generated by this pipeline are probabilistic historical research signals rather than guaranteed future price predictions.

---

## Executive Summary

### Gold
* **Current Price (USD/oz):** {g_price_str}
* **Current Price (INR/10g):** {g_inr_str}
* **Daily Move:** {g_move:+.2f}%
* **Research Bias:** {signals_summary.get('gold', {}).get('overall_research_bias', 'Neutral')}
* **Composite Score:** {scores_summary.get('composite_score', 'N/A')}/100

### Silver
* **Current Price (USD/oz):** {s_price_str}
* **Current Price (INR/kg):** {s_inr_str}
* **Daily Move:** {s_move:+.2f}%
* **Research Bias:** {signals_summary.get('silver', {}).get('overall_research_bias', 'Neutral')}

---

## Technical & Macro Overview

* **Market Regime:** {regime_summary.get('market_regime', 'N/A')}
* **Macro Regime:** {macro_summary.get('macro_regime', 'N/A')}
* **Gold/Silver Ratio:** {ratio_str} (Z-score: {zscore_str})
* **DXY:** {macro_summary.get('dxy_close', 'N/A')} ({macro_summary.get('dxy_return_20d', 0.0):+.2f}% 20d)
* **US 10Y Yield:** {macro_summary.get('us10y_close', 'N/A')}%

---

## Historical Analogue Analysis

Top historical analogue dates matching current multi-factor state:
"""
        analogues = analogue_summary.get("analogues", [])
        if analogues:
            for anal in analogues[:5]:
                md += f"- **{anal.get('date')}** (Similarity Score: {anal.get('similarity_score')}, Macro: {anal.get('macro_regime')})\n"
        else:
            md += "- No historical analogues found with sufficient similarity.\n"

        md += "\n--- \n\n## Forward Probability Statistics (Gold)\n\n"

        horizons = signals_summary.get("gold", {}).get("horizon_signals", {})
        if horizons:
            md += "| Horizon | Bias | P(Positive) | Historical Mean Return | Confidence |\n"
            md += "|---|---|---|---|---|\n"
            for h_str, sig in horizons.items():
                mean_ret = sig.get('historical_mean_return_pct', 0.0) or 0.0
                md += f"| {h_str} | {sig.get('research_bias')} | {sig.get('probability_positive_return_pct')}% | {mean_ret:+.2f}% | {sig.get('confidence_score')}/100 |\n"

        md += f"""
---

## Data Quality Audit
* **Total Valid Records:** {quality_summary.get('valid_records', 'N/A')}
* **Suspicious Records:** {quality_summary.get('suspicious_records', 'N/A')}
* **Warnings:** {quality_summary.get('warnings', [])}

---
*Report automatically generated by Gold & Silver Market Pipeline.*
"""

        os.makedirs(self.reports_dir, exist_ok=True)
        report_path = os.path.join(self.reports_dir, f"{target_date}.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(md)

        # Machine readable JSON
        json_data = {
            "date": target_date,
            "gold": gold_summary,
            "silver": silver_summary,
            "gold_silver_ratio": ratio_summary,
            "macro": macro_summary,
            "market_regime": regime_summary,
            "scores": scores_summary,
            "signals": signals_summary,
            "analogues": analogue_summary,
            "data_quality": quality_summary,
        }

        os.makedirs(self.analysis_dir, exist_ok=True)
        json_path = os.path.join(self.analysis_dir, f"{target_date}.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_data, f, indent=2)

        return report_path
